name: llm-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.1
  - spacy>=3.6.1
  - numpy>=1.24.3
  - pandas>=1.5.3
  - scikit-learn>=1.3.0
  - pip
  - pip:
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl
