default_model: claude-2.1
models:
  claude2:
    name: claude-2.1
    max_tokens: 100000
    temperature: 0.7
  claude_instant:
    name: claude-instant-1.2
    max_tokens: 100000
    temperature: 0.7
api:
  timeout: 60
  max_retries: 3