llm:
  provider: openai
  model_name: gpt-4-1106-preview
  temperature: 0.7
  streaming: true

embeddings:
  provider: openai
  model_name: text-embedding-ada-002

memory:
  type: buffer_window
  k: 5
  return_messages: true

callbacks:
  - type: streaming
  - type: logging

agents:
  type: zero_shot_react_description
  max_iterations: 5
  early_stopping_method: generate

retrievers:
  type: vector_store
  search_type: similarity
  k: 4

chains:
  type: stuff
  verbose: true