default_model: gpt-4-1106-preview
models:
  gpt4_turbo:
    name: gpt-4-1106-preview
    max_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
  gpt4:
    name: gpt-4
    max_tokens: 8192
    temperature: 0.7
  gpt35_turbo:
    name: gpt-3.5-turbo-1106
    max_tokens: 4096
    temperature: 0.7
embeddings:
  default: text-embedding-ada-002
  dimensions: 1536
  batch_size: 100
api:
  timeout: 60
  max_retries: 3
  retry_delay: 1